# Generated by Django 5.2.1 on 2025-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapehelper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmigration',
            name='var3',
            field=models.CharField(default='undef'),
            preserve_default=False,
        ),
    ]
